/**
 * RoutesManager - Route Configuration Management Module
 * 
 * Provides configuration-level route management for virtual model categories
 * and routing tables. Generates configuration data consumed by routing engines.
 * 
 * Features:
 * - Virtual model category definitions (default, coding, reasoning, etc.)
 * - Route configuration tables with target mappings
 * - Load balancing strategy configuration (not execution)
 * - Route target configuration management
 * - Configuration export for routing engines
 * 
 * Note: This module only manages route CONFIGURATION, not actual routing execution.
 * The actual load balancing and request routing is handled by routing engines
 * that consume the configuration generated by this module.
 * 
 * @module RoutesManager
 */

export { RoutesManager } from './RoutesManager';
export type {
  IRoutesManager,
  IRoute,
  IRouteTarget,
  IVirtualModelCategory,
  ILoadBalancingStrategy,
  IRoutingOptions,
  IRouteSelectionResult,
  IRouteHealthStatus,
  IRoutingMetrics
} from './interfaces/IRoutesManager';